### ISSUE TITLE
Error in model loading when called predict method

### ISSUE THREAD

**Issue by pritamfocal** [HumanSignal/label-studio-ml-backend#307]
I am trying to integrate SAM.The model is getting loaded but when I try to annotate. I am getting this error here. I will really appreciate any help on this

 (mask_decoder): MaskDecoder(
  (transformer): TwoWayTransformer(
   (layers): ModuleList(
    (0): TwoWayAttentionBlock(
     (self_attn): Attention(
      (q_proj): Linear(in_features=256, out_features=256, bias=True)
      (k_proj): Linear(in_features=256, out_features=256, bias=True)
      (v_proj): Linear(in_features=256, out_features=256, bias=True)
      (out_proj): Linear(in_features=256, out_features=256, bias=True)
     )
     (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (cross_attn_token_to_image): Attention(
      (q_proj): Linear(in_features=256, out_features=128, bias=True)
      (k_proj): Linear(in_features=256, out_features=128, bias=True)
      (v_proj): Linear(in_features=256, out_features=128, bias=True)
      (out_proj): Linear(in_features=128, out_features=256, bias=True)
     )
     (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (mlp): MLPBlock(
      (lin1): Linear(in_features=256, out_features=2048, bias=True)
      (lin2): Linear(in_features=2048, out_features=256, bias=True)
      (act): ReLU()
     )
     (norm3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (norm4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (cross_attn_image_to_token): Attention(
      (q_proj): Linear(in_features=256, out_features=128, bias=True)
      (k_proj): Linear(in_features=256, out_features=128, bias=True)
      (v_proj): Linear(in_features=256, out_features=128, bias=True)
      (out_proj): Linear(in_features=128, out_features=256, bias=True)
     )
    )
    (1): TwoWayAttentionBlock(
     (self_attn): Attention(
      (q_proj): Linear(in_features=256, out_features=256, bias=True)
      (k_proj): Linear(in_features=256, out_features=256, bias=True)
      (v_proj): Linear(in_features=256, out_features=256, bias=True)
      (out_proj): Linear(in_features=256, out_features=256, bias=True)
     )
     (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (cross_attn_token_to_image): Attention(
      (q_proj): Linear(in_features=256, out_features=128, bias=True)
      (k_proj): Linear(in_features=256, out_features=128, bias=True)
      (v_proj): Linear(in_features=256, out_features=128, bias=True)
      (out_proj): Linear(in_features=128, out_features=256, bias=True)
     )
     (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (mlp): MLPBlock(
      (lin1): Linear(in_features=256, out_features=2048, bias=True)
      (lin2): Linear(in_features=2048, out_features=256, bias=True)
      (act): ReLU()
     )
     (norm3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (norm4): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
     (cross_attn_image_to_token): Attention(
      (q_proj): Linear(in_features=256, out_features=128, bias=True)
      (k_proj): Linear(in_features=256, out_features=128, bias=True)
      (v_proj): Linear(in_features=256, out_features=128, bias=True)
      (out_proj): Linear(in_features=128, out_features=256, bias=True)
     )
    )
   )
   (final_attn_token_to_image): Attention(
    (q_proj): Linear(in_features=256, out_features=128, bias=True)
    (k_proj): Linear(in_features=256, out_features=128, bias=True)
    (v_proj): Linear(in_features=256, out_features=128, bias=True)
    (out_proj): Linear(in_features=128, out_features=256, bias=True)
   )
   (norm_final_attn): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  )
  (iou_token): Embedding(1, 256)
  (mask_tokens): Embedding(4, 256)
  (output_upscaling): Sequential(
   (0): ConvTranspose2d(256, 64, kernel_size=(2, 2), stride=(2, 2))
   (1): LayerNorm2d()
   (2): GELU(approximate='none')
   (3): ConvTranspose2d(64, 32, kernel_size=(2, 2), stride=(2, 2))
   (4): GELU(approximate='none')
  )
  (output_hypernetworks_mlps): ModuleList(
   (0): MLP(
    (layers): ModuleList(
     (0): Linear(in_features=256, out_features=256, bias=True)
     (1): Linear(in_features=256, out_features=256, bias=True)
     (2): Linear(in_features=256, out_features=32, bias=True)
    )
   )
   (1): MLP(
    (layers): ModuleList(
     (0): Linear(in_features=256, out_features=256, bias=True)
     (1): Linear(in_features=256, out_features=256, bias=True)
     (2): Linear(in_features=256, out_features=32, bias=True)
    )
   )
   (2): MLP(
    (layers): ModuleList(
     (0): Linear(in_features=256, out_features=256, bias=True)
     (1): Linear(in_features=256, out_features=256, bias=True)
     (2): Linear(in_features=256, out_features=32, bias=True)
    )
   )
   (3): MLP(
    (layers): ModuleList(
     (0): Linear(in_features=256, out_features=256, bias=True)
     (1): Linear(in_features=256, out_features=256, bias=True)
     (2): Linear(in_features=256, out_features=32, bias=True)
    )
   )
  )
  (iou_prediction_head): MLP(
   (layers): ModuleList(
    (0): Linear(in_features=256, out_features=256, bias=True)
    (1): Linear(in_features=256, out_features=256, bias=True)
    (2): Linear(in_features=256, out_features=4, bias=True)
   )
  )
 )
)
[2023-08-06 16:43:21,132] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
  return f(*args, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
  predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
 File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 615, in predict
  raise ValueError(f'Model is not loaded for {cls.__class__.__name__}: run setup() before using predict()')
ValueError: Model is not loaded for type: run setup() before using predict()
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
  return f(*args, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
  predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
 File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 615, in predict
  raise ValueError(f'Model is not loaded for {cls.__class__.__name__}: run setup() before using predict()')
ValueError: Model is not loaded for type: run setup() before using predict()

**Comment by 106firestarter** [comment]
same here, different model and different implementation but the issues is the same. Apparently the model is not loaded when the predict is called. This does not always happen and I'm still able to get predictions, however, it fails and when it fails it is due to this issue.
