### ISSUE TITLE
default_config

### ISSUE THREAD

**Issue by d3vopz-net** [HumanSignal/label-studio-ml-backend#321]

**Comment by d3vopz-net** [comment]
next is 
```
Running setup.py install for uwsgi: started
  Running setup.py install for uwsgi: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for uwsgi did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
        warnings.warn(msg)
      running install
      using profile: buildconf/default.ini
      detected include path: ['/usr/include', '/usr/local/include']
      Traceback (most recent call last):
        File "/tmp/pip-install-njxyo9af/uwsgi_a7f76216da8e4f3f955d60d90ef8a392/uwsgiconfig.py", line 747, in __init__
          gcc_version_components = gcc_version.split('.')
      AttributeError: 'NoneType' object has no attribute 'split'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-njxyo9af/uwsgi_a7f76216da8e4f3f955d60d90ef8a392/setup.py", line 117, in <module>
          setup(
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-njxyo9af/uwsgi_a7f76216da8e4f3f955d60d90ef8a392/setup.py", line 77, in run
          conf = uc.uConf(get_profile())
        File "/tmp/pip-install-njxyo9af/uwsgi_a7f76216da8e4f3f955d60d90ef8a392/uwsgiconfig.py", line 755, in __init__
          raise Exception("you need a C compiler to build uWSGI")
      Exception: you need a C compiler to build uWSGI
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> uwsgi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

```

**Comment by d3vopz-net** [comment]
next is:
```
docker-compose up
Creating network "ner-20230819125600_default" with the default driver
Creating redis ... done
Creating server ... done
Attaching to redis, server
server    | /bin/sh: 1: exec: gunicorn: not found
redis     | 1:C 19 Aug 2023 21:33:28.851 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis     | 1:C 19 Aug 2023 21:33:28.851 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
redis     | 1:C 19 Aug 2023 21:33:28.851 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis     | 1:M 19 Aug 2023 21:33:28.851 * monotonic clock: POSIX clock_gettime
```

**Comment by d3vopz-net** [comment]
next is

```
docker-compose up

server    | Traceback (most recent call last):
server    |   File "/usr/local/bin/gunicorn", line 8, in <module>
server    |     sys.exit(run())
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
server    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 236, in run
server    |     super().run()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
server    |     Arbiter(self).run()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
server    |     self.setup(app)
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
server    |     self.app.wsgi()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
server    |     self.callable = self.load()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
server    |     return self.load_wsgiapp()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
server    |     return util.import_app(self.app_uri)
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
server    |     mod = importlib.import_module(module)
server    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
server    |     return _bootstrap._gcd_import(name[level:], package, level)
server    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
server    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
server    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
server    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
server    |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
server    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
server    |   File "/app/_wsgi.py", line 32, in <module>
server    |     from ner import TransformersBasedTagger
server    |   File "/app/ner.py", line 467
server    |     def fit(
server    |     ^
server    | SyntaxError: invalid syntax
```

**Comment by d3vopz-net** [comment]
next is 
```
docker-compose up


Attaching to server
server    | [2023-08-19 22:05:35,098] [ERROR] [ner::predict::369] No model loaded! Please train model before getting predictions!
server    | [2023-08-19 22:05:35,776] [ERROR] [ner::predict::369] No model loaded! Please train model before getting predictions!
server    | [2023-08-19 22:05:55,266] [ERROR] [ner::predict::369] No model loaded! Please train model before getting predictions!
```

**Comment by EtienneFerrandi** [comment]
did you solve the last problem ?
