### ISSUE TITLE
docker-compose up in default_configs ModuleNotFoundError: No module named '_wsgi'

### ISSUE THREAD

**Issue by d3vopz-net** [HumanSignal/label-studio-ml-backend#322]
docker-compose up
Creating network "default_configs_default" with the default driver
Creating ml-backend ... done
Attaching to ml-backend
ml-backend    | Traceback (most recent call last):
ml-backend    |   File "/usr/local/bin/gunicorn", line 8, in <module>
ml-backend    |     sys.exit(run())
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
ml-backend    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
ml-backend    |     super().run()
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
ml-backend    |     Arbiter(self).run()
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
ml-backend    |     self.setup(app)
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
ml-backend    |     self.app.wsgi()
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
ml-backend    |     self.callable = self.load()
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ml-backend    |     return self.load_wsgiapp()
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ml-backend    |     return util.import_app(self.app_uri)
ml-backend    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
ml-backend    |     mod = importlib.import_module(module)
ml-backend    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ml-backend    |     return _bootstrap._gcd_import(name[level:], package, level)
ml-backend    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ml-backend    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ml-backend    |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ml-backend    | ModuleNotFoundError: No module named '_wsgi'

**Comment by d3vopz-net** [comment]
`docker-compose up` or `docker-compose build` does transform `_wsgi.py.tmpl` to a valid `_wsgi.py`. Please fix Dockerfile or change `README.md`

**Comment by gpsamt** [comment]
Estou tento o mesmo erro. Já fiz de tudo, instalei reinstalei e continua tento essa mensagem de erro. 
Estou usando em uma maquina com windows11. 
Tenho 10 mil imagens para rotular em 4 classes diferentes. Não consigo fazer na mão. Preciso conseguir rodar esse back-end.

**Comment by koshyviv** [comment]
The Readme is correct, instead of running `docker-compose up` in `default_configs` - you need to run it within the example you want after editing the `docker-compose.yml`

Eg:
```
cd tmp/label-studio-ml-backend/label_studio_ml/examples/segment_anything_model
docker-compose up
```
