### ISSUE TITLE
parsed_label_config: TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by nabilr** [HumanSignal/label-studio-ml-backend#343]
[2023-08-30 19:05:45,482] [INFO] [werkzeug::_log::187] 10.27.86.50 - - [30/Aug/2023 19:05:45] "GET /health HTTP/1.1" 200 -
nabil
[2023-08-30 19:05:45,667] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/Users/nr83/git/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/Users/nr83/git/label-studio-ml-backend/label_studio_ml/api.py", line 71, in _setup
    model = MODEL_CLASS(project_id)
  File "/Users/nr83/git/label-studio-ml-backend/my_ml_backend/pytorch_transfer_learning.py", line 159, in __init__
    print( self.parsed_label_config)
  File "/Users/nr83/git/label-studio-ml-backend/label_studio_ml/model.py", line 64, in parsed_label_config
    return json.loads(self.get('parsed_label_config'))
  File "/Users/nr83/anaconda3/envs/label_studio/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Traceback (most recent call last):
  File "/Users/nr83/git/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/Users/nr83/git/label-studio-ml-backend/label_studio_ml/api.py", line 71, in _setup
    model = MODEL_CLASS(project_id)
  File "/Users/nr83/git/label-studio-ml-backend/my_ml_backend/pytorch_transfer_learning.py", line 159, in __init__
    print( self.parsed_label_config)
  File "/Users/nr83/git/label-studio-ml-backend/label_studio_ml/model.py", line 64, in parsed_label_config
    return json.loads(self.get('parsed_label_config'))
  File "/Users/nr83/anaconda3/envs/label_studio/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

[2023-08-30 19:05:45,667] [INFO] [werkzeug::_log::187] 10.27.86.50 - - [30/Aug/2023 19:05:45] "POST /setup HTTP/1.1" 500 -

**Comment by kirillbiktya** [comment]
Same problem, backend inits well, but fails when attempting to add to labelstudio project

**Comment by nabilr** [comment]
Here is the workaround to solve it.
diff --git a/label_studio_ml/api.py b/label_studio_ml/api.py
index a34f3f7..e47d887 100644
--- a/label_studio_ml/api.py
+++ b/label_studio_ml/api.py
@@ -55,7 +55,7 @@ def _predict():
     label_config = data.get('label_config')
     context = params.pop('context', {})
 
-    model = MODEL_CLASS(project_id)
+    model = MODEL_CLASS(project_id, label_config)
     model.use_label_config(label_config)
 
     predictions = model.predict(tasks, context=context, **params)
@@ -66,9 +66,10 @@ def _predict():
 @exception_handler
 def _setup():
     data = request.json
+    print(data)
     project_id = data.get('project').split('.', 1)[0]
     label_config = data.get('schema')
-    model = MODEL_CLASS(project_id)
+    model = MODEL_CLASS(project_id,label_config)
     model.use_label_config(label_config)
     model_version = model.get('model_version')
     return jsonify({'model_version': model_version})
@@ -90,7 +91,7 @@ def webhook():
         return jsonify({'status': 'Unknown event'}), 200
     project_id = str(data['project']['id'])
     label_config = data['project']['label_config']
-    model = MODEL_CLASS(project_id)
+    model = MODEL_CLASS(project_id, label_config)
     model.use_label_config(label_config)
     model.fit(event, data)
     return jsonify({}), 201




class YOLOv8Model(LabelStudioMLBase):
    def __init__(self, projectid, label_config):
        
        # Call base class constructor
        super(YOLOv8Model, self).__init__(projectid).  <<<<<<<<<<Added these two lines
        self.use_label_config(label_config)           <<<<<<<<<<<<<<<

        from_name, schema = list(self.parsed_label_config.items())[0]
        self.from_name = from_name
        self.to_name = schema['to_name'][0]
        self.labels = ['worm']
        # self.model = YOLO("best.pt")

**Comment by stronquens** [comment]
Hi, same issue for me running on docker. With pip ml backend works perfect but when i use the docker compose generated by the command "label-studio-ml create ml_backend" appears this error.

ml-backend    | Traceback (most recent call last):
ml-backend    |   File "/usr/local/lib/python3.10/dist-packages/label_studio_ml/exceptions.py", line 39, in exception_f
ml-backend    |     return f(*args, **kwargs)
ml-backend    |   File "/usr/local/lib/python3.10/dist-packages/label_studio_ml/api.py", line 71, in _setup
ml-backend    |     model = MODEL_CLASS(project_id)
ml-backend    |   File "/app/model.py", line 24, in __init__
ml-backend    |     self.parsed_label_config, 'RectangleLabels', 'Image')
ml-backend    |   File "/usr/local/lib/python3.10/dist-packages/label_studio_ml/model.py", line 83, in parsed_label_config
ml-backend    |     return json.loads(self.get('parsed_label_config'))
ml-backend    |   File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
ml-backend    |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
ml-backend    | TypeError: the JSON object must be str, bytes or bytearray, not NoneType
ml-backend    |
